[package]
name = "upfind"
version = "1.0.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
git2 = "0.18.1"
gethostname = "0.4.3"

[profile.release]
strip = true
